# Generated by Django 4.2.4 on 2023-08-09 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, verbose_name="Nome")),
                ("value", models.FloatField(verbose_name="Valor")),
                ("status", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Data"
                    ),
                ),
            ],
        ),
    ]
