# Generated by Django 4.2.4 on 2023-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investment",
            options={
                "verbose_name": "Investimento",
                "verbose_name_plural": "Investimentos",
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="description",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
