# Generated by Django 4.2.4 on 2023-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="categoria")),
                ("essential", models.BooleanField(default=False)),
                ("planning_value", models.FloatField(default=0)),
            ],
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias",},
        ),
    ]
