# Generated by Django 4.2.4 on 2023-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="essential",
            field=models.BooleanField(default=False, verbose_name="essêncial"),
        ),
        migrations.AlterField(
            model_name="category",
            name="planning_value",
            field=models.FloatField(default=0, verbose_name="Valor de planejamento"),
        ),
    ]
