# Generated by Django 4.2.4 on 2023-08-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Conta", "verbose_name_plural": "Contas"},
        ),
    ]
