# Generated by Django 4.2.4 on 2023-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0005_alter_account_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.CharField(
                choices=[
                    ("Nu", "Nubank"),
                    ("BB", "Banco do Brasil"),
                    ("CE", "Caixa Econômica Federal"),
                    ("IT", "Itaú Unibanco"),
                    ("SA", "Santander"),
                    ("BR", "Bradesco"),
                    ("HS", "HSBC"),
                    ("CT", "Citibank"),
                    ("BN", "BNDES"),
                    ("BP", "Banco Pan"),
                    ("SC", "Sicoob"),
                    ("IN", "Banco Inter"),
                    ("CB", "C6 Bank"),
                    ("BancoOriginal", "Banco Original"),
                    ("SF", "Banco Safra"),
                    ("NE", "Next"),
                    ("NE", "Neon"),
                    ("BD", "BTG Pactual"),
                    ("BA", "Banco Daycoval"),
                    ("XP", "XP Investimentos"),
                ],
                max_length=20,
                verbose_name="Banco",
            ),
        ),
    ]
