# Generated by Django 4.2.4 on 2023-09-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial", "0006_alter_account_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill_to_pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Título")),
                ("description", models.TextField()),
                ("value", models.FloatField()),
                ("bill_day", models.ImageField(upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="financial.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia do Pagamento",
                "verbose_name_plural": "Dias dos Pagamentos",
            },
        ),
    ]
