# Generated by Django 4.2.4 on 2023-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_to_pay",
            name="bill_day",
            field=models.IntegerField(verbose_name="Dia do pagamento"),
        ),
        migrations.AlterField(
            model_name="bill_to_pay",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="bill_to_pay",
            name="value",
            field=models.FloatField(verbose_name="Valor"),
        ),
    ]
