# Generated by Django 4.2.4 on 2023-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_paidbills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_to_pay",
            name="bill_day",
            field=models.DateField(verbose_name="Dia do pagamento"),
        ),
    ]
