# Generated by Django 4.2.4 on 2023-09-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_bill_to_pay_bill_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paidbills",
            options={
                "verbose_name": "Conta paga",
                "verbose_name_plural": "Contas pagas",
            },
        ),
    ]
