# Generated by Django 4.2.4 on 2023-08-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extract", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="values",
            options={"verbose_name": "Valor", "verbose_name_plural": "Valores"},
        ),
    ]
